hms/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homeapp.urls')),
    path('profile/', include('profileapp.urls')),
    path('contact/', include('contactapp.urls')),
    path('blogs/', include('blogapp.urls')),

    path('summernote/', include('django_summernote.urls')),
]
if settings.DEBUG:
    #urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

homeapp/urls.py
from django.urls import path

from .import views

app_name='homeapp'

urlpatterns = [
    path('', views.home, name='homepage'),
    path('about/', views.about, name='aboutpage'),
    path('doctor/', views.doctor, name='doctorpage'),
    path('doctor/<int:pk>', views.doctor_details, name='doctor_details_page'),
    path('reviews/', views.review, name='reviewpage'),
    path('services/', views.services, name='services_page'),
    path('services_details/<int:pk>', views.services_details, name='services_details_page'),
    path('department/<int:pk>', views.department_details, name='departmentdetails'),
    path('test_price_list/', views.test_price_list, name='test_price_list'), 
    path('diagnostic/<int:pk>', views.diagnostic_details, name='diagnostic_details'),
    path('hospital/', views.hospital, name='hospital_page'),
    path('hospital/<int:pk>', views.hospital_details, name='hospital_details'),
] 

homeapp/models.py
from django.db import models
from profileapp.models import Doctor
from django.utils.html import mark_safe
from django.conf import settings


class Department(models.Model):
    name = models.CharField(max_length=200)
    image= models.ImageField(null=True,blank=True, default="avatar.svg")
    details=models.TextField()
    deptdoctor = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True,related_name='doctor_name')

    def __str__(self):
        return str(self.name) 

    def image_tag(self):
        if self.image != '':
            return mark_safe('<img src="%s%s" width="50" height="50" />' % (f'{settings.MEDIA_URL}', self.image))

class Services(models.Model):
    name = models.CharField(max_length=200,null=True,blank=True)
    image= models.ImageField(null=True,blank=True, default="avatar.svg")
    details=models.TextField(null=True,blank=True)

    def __str__(self):
        return str(self.name)

    def image_tag(self):
        if self.image != '':
            return mark_safe('<img src="%s%s" width="50" height="50" />' % (f'{settings.MEDIA_URL}', self.image))

class Diagnostic(models.Model):
    name = models.CharField(max_length=200,null=True,blank=True)
    image= models.ImageField(null=True,blank=True, default="avatar.svg")
    details=models.TextField(null=True,blank=True)

    def __str__(self):
        return str(self.name)

    def image_tag(self):
        if self.image != '':
            return mark_safe('<img src="%s%s" width="50" height="50" />' % (f'{settings.MEDIA_URL}', self.image))

class Hospital(models.Model):
    name = models.CharField(max_length=200,null=True,blank=True)
    image= models.ImageField(null=True,blank=True, default="avatar.svg")
    details=models.TextField(null=True,blank=True)

    def __str__(self):
        return str(self.name)

    def image_tag(self):
        if self.image != '':
            return mark_safe('<img src="%s%s" width="50" height="50" />' % (f'{settings.MEDIA_URL}', self.image))
    

class Laboratory(models.Model):
    testname=models.CharField(max_length=100)
    costoftest=models.IntegerField(blank=True, null=True)
    resulttime=models.TimeField()

    def __str__(self):
        return str(self.testname)

    
class Gallery(models.Model):
    image=models.ImageField(upload_to='gallery_img', blank=True, null=True)
    title=models.CharField( max_length=20, blank=True, null=True)
    text=models.CharField(max_length=50, blank=True, null=True)


class Review(models.Model):
    name=models.CharField( max_length=20, blank=True, null=True)
    title=models.CharField( max_length=20, blank=True, null=True)
    text=models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return str(self.name)

homeapp/views.py
from django.shortcuts import render
from profileapp.models import Doctor
from homeapp.models import Review,Department,Laboratory,Services,Hospital,Diagnostic
from contactapp.models import Appointment
from django.contrib import messages

# dob_month = int(dob_month),
def home(request):
    doctors = Doctor.objects.all()[:4]
    departments = Department.objects.all()[:6]
    reviews = Review.objects.all()
    services = Services.objects.all()[:4]
    # object = Doctor.objects.get(pk=pk) 
    if request.method == "POST":
        # try:
            name = request.POST.get("name")
            phone = request.POST.get("phone")
            date = request.POST.get("date")
            department = request.POST.get("department")
            Appointment.objects.create(name=name,phone=phone,
            date=date, department_name=department)
            return render(request,'global/thankyou.html')
        # except:
        #     messages.warning(request, 'Please fill up all the form feild currectly!')

    return render(request,'homeapp/index.html',{'doctors':doctors,
    'departments':departments,'reviews':reviews,'services':services})

def about(request):
    doctors = Doctor.objects.all()[:4]
    reviews = Review.objects.all()
    return render(request,'homeapp/about.html',{'reviews':reviews,'doctors':doctors,})

def doctor(request):
    doctors = Doctor.objects.all()
    return render(request,'homeapp/doctor.html',{'doctors':doctors})

def doctor_details(request,pk):
    if request.method == "POST":
    # try:
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        date = request.POST.get("date")
        doctor_name = request.POST.get("doctor_name")
        Appointment.objects.create(name=name,phone=phone,
        date=date, doctor_name=doctor_name)
        return render(request,'global/thankyou.html')
    object = Doctor.objects.get(pk=pk)
    return render(request,'homeapp/doctor_details.html',{'object':object})

def review(request):
    reviews = Review.objects.all()
    return render(request,'homeapp/review.html',{'reviews':reviews})

def test_price_list(request):
    laboratorys = Laboratory.objects.all()
    return render(request,'homeapp/test_price.html',{'laboratorys':laboratorys}) 


def services(request): 
    services = Services.objects.all() 
    return render(request,'homeapp/services.html',{'services':services})

def services_details(request,pk):
    if request.method == "POST":
        # try:
            name = request.POST.get("name")
            phone = request.POST.get("phone")
            date = request.POST.get("date")
            service_name = request.POST.get("service_name")
            Appointment.objects.create(name=name,phone=phone,
            date=date, department_name=service_name)
            return render(request,'global/thankyou.html') 
    object = Services.objects.get(pk=pk) 
    return render(request,'homeapp/services_details.html',{'object':object})

def department_details(request,pk):
    if request.method == "POST":
        # try:
            name = request.POST.get("name")
            phone = request.POST.get("phone")
            date = request.POST.get("date")
            department = request.POST.get("department")
            Appointment.objects.create(name=name,phone=phone,
            date=date, department_name=department)
            return render(request,'global/thankyou.html')
    object = Department.objects.get(pk=pk)
    return render(request,'homeapp/depertment_details.html',{'object':object}) 

def diagnostic_details(request,pk):  
    if request.method == "POST":
        # try:
            name = request.POST.get("name")
            phone = request.POST.get("phone")
            date = request.POST.get("date")
            department = request.POST.get("department")
            Appointment.objects.create(name=name,phone=phone,
            date=date, department_name=department) 
            return render(request,'global/thankyou.html')
    object = Diagnostic.objects.get(pk=pk)
    return render(request,'homeapp/diagnostic_details.html',{'object':object}) 

def hospital(request): 
    hospital = Hospital.objects.all() 
    return render(request,'homeapp/hospital.html',{'hospital':hospital})  

def hospital_details(request,pk):
    if request.method == "POST":
        # try:
            name = request.POST.get("name") 
            phone = request.POST.get("phone")
            date = request.POST.get("date")
            department = request.POST.get("department")
            Appointment.objects.create(name=name,phone=phone,
            date=date, department_name=department) 
            return render(request,'global/thankyou.html')
    object = Hospital.objects.get(pk=pk)
    return render(request,'homeapp/hospital_details.html',{'object':object}) 




    

templates/homeapp/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


	
<section class="inner-header">
   <div class="container">
      <div class="row">
         <div class="col-md-12 sec-title colored text-center">
            <h2>About Us</h2>
            <ul class="breadcumb">
               <li><a href="index.html">Home</a></li>
               <li><i class="fa fa-angle-right"></i></li>
               <li><span>About Us</span></li>
            </ul>
            <span class="decor"><span class="inner"></span></span>
         </div>
      </div>
   </div>
</section>

<section class="sec-pdd-90 about-content full-sec">
   <div class="container">
      <div class="row">
         <div class="col-lg-6 col-md-12">
            <div class="full-sec-content">
               <div class="sec-title style-two">
                  <h2>More about us</h2>
                  <span class="decor">
                     <span class="inner"></span>
                  </span>
               </div>
               <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dignissim orci ut aliquet mollis. 
                  Duis varius leo vel justo malesuada, non imperdiet ligula mattis. Sed et malesuada dui. Nam eros libero, elementum eget magna ac, mollis aliquam ex. Integer ut enim porta, sollicitudin nisi a, tincidunt magna. Sed molestie feugiat ligula, et porttitor leo luctus mattis. Aenean maximus pulvinar ipsum eget congue. In nec enim tincidunt, aliquet leo at, interdum libero.
                   Nulla facilisi. Aliquam erat volutpat. Donec sit amet odio vitae nisl imperdiet scelerisque.</p>
            </div>
         </div>
         <div class="col-md-6 hidden-md text-right itm-mgn-top-50">
            <img src="{% static 'img/resources/about-1.jpg' %}" alt="Awesome Image"/>
         </div>
      </div>
   </div>
</section> 



<section class="sec-pdd-90 meet-doctors gray-bg">
   <div class="container">
      <div class="sec-title text-left">
         <h2>Meet Our Doctors</h2>
         <p>Lorem ipsum is a dummy text it will use for subtitle here</p>
         <span class="decor"><span class="inner"></span></span>
      </div>
      <div class="clearfix">
         <div class="team-carousel owl-carousel owl-theme">

         {% for doctor in doctors %} 
            <div class="item">
               <div class="single-team-member">
                  <div class="img-box">
                     <img src="{{doctor.image.url}}" alt=""> 
                     <div class="overlay">
                        <div class="box">
                           <div class="content">
                              <ul>
                                 <li><a href="#"><i class="fa fa-plus"></i></a></li>
                              </ul>
                           </div>
                        </div>
                     </div>
                  </div>
                  <h3>{{doctor.name }}</h3>
                  <span>{{doctor.speciallist }}</span>

                  <a href="{% url 'homeapp:doctor_details_page' doctor.pk %}" class="thm-btn">View Profile</a>
               </div>
            </div>
            {% endfor %}


         </div>
      </div>
   </div>
</section>



<section class="sec-pdd-90-80 testimonials-wrapper">
   <div class="container">
      <div class="sec-title colored text-center">
         <h2>Testimonials</h2>
         <span class="decor">
            <span class="inner"></span>
         </span>
      </div>
      <div class="testimonaials-carousel owl-carousel owl-theme">
 
         {% for review in reviews %}
         <div class="item">
            <div class="single-testimonaials"> 
               <div class="qoute-box">
                  <i class="qoute">“</i>
               </div>
               <p>{{review.text|truncatechars:50}}</p>
               <h3>{{review.name}}</h3>
               <span>{{review.title}}</span>
            </div>
         </div>
         {% endfor %}


      </div>
   </div>
</section>

 {% endblock %}

templates/homeapp/depertment_details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<section class="inner-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12 sec-title colored text-center">
                <h2>{{object.name}}</h2>
                <ul class="breadcumb">
                    <li><a href="#">Home</a></li>
                    <li><i class="fa fa-angle-right"></i></li>
                    <li><span>{{object.name}}</span></li>
                </ul>
                <span class="decor"><span class="inner"></span></span>
            </div>
        </div>
    </div>
</section>

<section id="single_Service" class="sec-pdd-90">
    <div class="container">
        <div class="row">
        
            <div class="col-lg-3 col-md-3">
                <div class="service_sideber">

                    
                    <div class="appointment-content appointment_side_form ">
                        <h2>Make An Appoinment</h2>
                        <form action="" method="POST" class="side_form contact-form" > 
                         {% csrf_token %}
                            <input class="" type="text"  placeholder="Full name" name="name" />
                            <input type="text"  placeholder="Phone" name="phone"/>
                            <input type="text" class="date-picker" name="date" placeholder="Select Date">
                            <div class="select-input-wrapper">
                                <select class="select-input" name="department">
                                    <option value="{{object.name}} " selected="selected">{{object.name}} </option>
                                </select>
                            </div>
                            <button type="submit" class="btn-info appoin_button">BOOK NOW</button>
                        </form>
                    </div>
                    
                    
                    <div class="question_Box">
                        <h2>Any Question ? Contact us</h2>
                        <hr />
                        
                        <div class="qustion_list">
                            <ul>
                                <li><i class="flaticon-telephone5"></i><a href="#">+082 01723801729</a></li>
                                <li><i class="flaticon-email147"></i><a href="#">companymail@gmail.com</a></li>
                            </ul>
                        </div>
                        
                    </div>
                    
                </div>
            </div>
            
            <div class="col-lg-9 col-md-9">
                <div class="tab-content">
                    <div class="service_mainconetent" id="invisalign">
                    
                        <div class="about_box">
                            <img src="{{ object.image.url }}"  alt="" />
                            <h2>{{object.name}} </h2>  
                            <p>{{object.details|safe}}</p>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock %}

templates/homeapp/detail.html
{% extends 'blogapp/main.html' %}
{% load static %}
{% block content %}
    
        <div class="blog-single gray-bg header-margin">
          <div class="container">
              <div class="row align-items-start">
                  <div class="col-lg-8 m-15px-tb">
                      <article class="article">
                          <div class="article-img">
                              <img src="{{ object.image.url }}" title="" alt="">
                          </div>
                          <div class="article-title">
                              
                              <h2>{{object.title}}</h2>
                              <div class="media second-header">
                                  <div class="avatar">
                                      <img src="{{ object.author.profile_pic.url }}"  title="" alt="">
                                  </div>
                                  <div class="media-body second-header-part">
                                      <label>{{user.username}}</label>
                                      <span>{{object.date}}</span>
                                      <label>Total views {{object.view_count}} times</label>
                                  </div>
                              </div>
                          </div>
                          <div class="article-content">
                              <p>{{object.details}}</p>
                          </div>
                          
                          <!-- {% if user.is_authenticated %}
                            {% if user.id == post.author.id %}
                             {% endif %}
                            {% endif %} -->
                        
                            {% if user.is_authenticated %}
                              <div class="nav tag-cloud">
                                  <a href="{% url 'blogapp:post-update' object.id %}">Update post</a>
                                  <a href="{% url 'blogapp:post-delete' object.id %}">Delete Post</a>
    
                              </div>
                            {% endif %} 
                      </article>


  <div class="contact-form article-comment">
                          {% comment %} <h4>Leave a Reply</h4> {% endcomment %}
                          <form id="contact-form" method="POST">
                              <div class="row">
                                  <div class="col-md-6">
                                      {% comment %} <div class="form-group">
                                          <input name="Name" id="name" placeholder="Name *" class="form-control" type="text">
                                      </div> {% endcomment %}
                                  </div>
                                  <div class="col-md-6">
                                      {% comment %} <div class="form-group">
                                          <input name="Email" id="email" placeholder="Email *" class="form-control" type="email">
                                      </div> {% endcomment %}
                                  </div>
                                  <div class="col-md-12">
                                      {% comment %} <div class="form-group">
                                          <textarea name="message" id="message" placeholder="Your message *" rows="4" class="form-control"></textarea>
                                      </div> {% endcomment %}
                                  </div>
                                  <div class="col-md-12">
                                      {% comment %} <div class="send">
                                          <button class="px-btn theme"><span>Submit</span> <i class="arrow"></i></button>
                                      </div> {% endcomment %}
                                  </div>
                              </div>
                          </form>
                      </div>
                  </div>



                  <div class="col-lg-4 m-15px-tb blog-aside">
    
                    <!-- Latest Post -->
                    <div class="widget widget-latest-post">
                        <div class="widget-title">
                            <h3>Latest Post</h3>
                        </div>
                          
                        <div class="widget-body">
                            {% for post in latest %}
                            <div class="latest-post-aside media">
                                <div class="lpa-left media-body">
                                    <div class="lpa-title">
                                        <h5><a href="{{ post.get_absolute_url }}">{{post.title}}</a></h5>
                                    </div>
                                    <div class="lpa-meta">
                                        <a class="name" href="{{ post.get_absolute_url }}">
                                            {{ post.author }}
                                        </a>
                                        <a class="date" href="#">
                                            {{ post.date }}
                                        </a>
                                    </div>
                                </div>
                                <div class="lpa-right">
                                    <a href="#">
                                        <img src="{{post.image.url }}" title="" alt="">
                                    </a>
                                </div> 
                            </div>
                            {% endfor %}
                           
                        </div>
                    </div>
                    <!-- End Latest Post -->
                   
                </div>
                <!-- </div>
                </div>
                </div> -->


<!--Footer seaction------------------------------------------------------------------------------------->

  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        <strong>A blog with django </strong> by <a href="https://altafhosen.com">Hosen MD Altaf</a>.
      </p>
    </div>
  </footer>  


{% endblock %}

templates/homeapp/diagnostic_details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<section class="inner-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12 sec-title colored text-center">
                <h2>{{object.name}}</h2> 
                <ul class="breadcumb">
                    <li><a href="#">Home</a></li>
                    <li><i class="fa fa-angle-right"></i></li>
                    <li><span>{{object.name}}</span></li>
                </ul>
                <span class="decor"><span class="inner"></span></span>
            </div>
        </div>
    </div>
</section>

<section id="single_Service" class="sec-pdd-90">
    <div class="container">
        <div class="row">
        
            <div class="col-lg-3 col-md-3">
                <div class="service_sideber">

                    
                    <div class="appointment-content appointment_side_form ">
                        <h2>Make An Appoinment</h2>
                        <form action="" method="POST" class="side_form contact-form" > 
                         {% csrf_token %}
                            <input class="" type="text"  placeholder="Full name" name="name" />
                            <input type="text"  placeholder="Phone" name="phone"/>
                            <input type="text" class="date-picker" name="date" placeholder="Select Date">
                            <div class="select-input-wrapper">
                                <select class="select-input" name="department">
                                    <option value="{{object.name}} " selected="selected">{{object.name}} </option>
                                </select>
                            </div>
                            <button type="submit" class="btn-info appoin_button">BOOK NOW</button>
                        </form>
                    </div>
                    
                    
                    <div class="question_Box">
                        <h2>Any Question ? Contact us</h2>
                        <hr />
                        
                        <div class="qustion_list">
                            <ul>
                                <li><i class="flaticon-telephone5"></i><a href="#">+082 01723801729</a></li>
                                <li><i class="flaticon-email147"></i><a href="#">companymail@gmail.com</a></li>
                            </ul>
                        </div>    
                    </div>
                </div>
            </div>
            
            <div class="col-lg-9 col-md-9">
                <div class="tab-content">
                    <div class="service_mainconetent" id="invisalign">
                    
                        <div class="about_box">
                            <img src="{{ object.image.url }}"  alt="" />
                            <h2>{{object.name}} </h2>  
                            <p>{{object.details|safe}}</p>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock %}

templates/homeapp/doctor.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="inner-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12 sec-title colored text-center">
                <h2>Our Doctors</h2>
                <ul class="breadcumb">
                    <li><a href="index.html">Home</a></li>
                    <li><i class="fa fa-angle-right"></i></li>
                    <li><span>Our Doctors</span></li>
                </ul>
                <span class="decor"><span class="inner"></span></span>
            </div>
        </div>
    </div>
</section>


<section class="sec-pdd-top-90 meet-doctors team-page">
    <div class="container">
        <div class="row">

            {% for doctor in doctors %}
            <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="single-team-member">
                    <div class="img-box">
                        <img src="{{doctor.image.url}}" alt="">
                        <div class="overlay">
                            <div class="box">
                                <div class="content">
                                    <ul>
                                        <li><a href="#"><i class="fa fa-plus"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <h3>{{doctor.name}}</h3>
                    <span>{{doctor.speciallist}}</span> 
                    <a href="{% url 'homeapp:doctor_details_page' doctor.pk %}" class="thm-btn">View Profile</a>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</section>



{% endblock %}

templates/homeapp/hospital.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="inner-header">
   <div class="container">
      <div class="row">
         <div class="col-md-12 sec-title colored text-center">
            <h2>Hospital</h2>
            <ul class="breadcumb">
               <li><a href="#">Home</a></li>
               <li><i class="fa fa-angle-right"></i></li>
               <li><span>Hospital</span></li>
            </ul>
            <span class="decor"><span class="inner"></span></span>
         </div>
      </div>
   </div>
</section>

<section class="home-serivce sec-pdd-90">
   <div class="container">
      <div class="sec-title text-center">
         <h2>Our Hospital Service</h2>
         <p>Lorem ipsum is a dummy text it will use for subtitle here</p>
         <span class="decor"><span class="inner"></span></span>
      </div>
      <div class="row"> 
         {% for hos in hospital %}
         <div class="col-md-4 col-sm-6">
            <div class="single-service-home item-margin-top"> 
               {% comment %} <div class="icon-box">
                  <div class="inner-box">
                     <i class="flaticon-medical-3"></i>
                  </div>
               </div> {% endcomment %}
               <div class="content">
                  <h3>{{hos.name}}</h3>  
                  <p>{{hos.details|truncatechars_html:60|safe}}</p>
                  <a href="{% url 'homeapp:hospital_details' hos.pk %}">Read More</a>
               </div>
            </div>
         </div>
         {% endfor %}
      </div>
   </div>
</section>



{% endblock %}

templates/homeapp/services.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="inner-header">
   <div class="container">
      <div class="row">
         <div class="col-md-12 sec-title colored text-center">
            <h2>Services</h2>
            <ul class="breadcumb">
               <li><a href="#">Home</a></li>
               <li><i class="fa fa-angle-right"></i></li>
               <li><span>Services</span></li>
            </ul>
            <span class="decor"><span class="inner"></span></span>
         </div>
      </div>
   </div>
</section>



<section class="home-serivce sec-pdd-90">
   <div class="container">
      <div class="sec-title text-center">
         <h2>Our Service</h2>
         <p>Lorem ipsum is a dummy text it will use for subtitle here</p>
         <span class="decor"><span class="inner"></span></span>
      </div>
      <div class="row">


         {% for service in services %}
         <div class="col-md-4 col-sm-6">
            <div class="single-service-home item-margin-top">
               {% comment %} <div class="icon-box">
                  <div class="inner-box">
                     <i class="flaticon-medical-3"></i>
                  </div>
               </div> {% endcomment %}
               <div class="content">
                  <h3>{{service.name}}</h3> 
                  <p>{{service.details|truncatechars_html:60|safe}}</p>
                  <a href="{% url 'homeapp:services_details_page' service.pk %}">Read More</a>
               </div>
            </div>
         </div>
         {% endfor %}
      </div>
   </div>
</section>



{% endblock %}