blogapp/urls.py
from django.urls import path
from . import views

app_name='blogapp'

urlpatterns = [ 
    path('blog/', views.blog, name='blogs'),
    path('blog_details/<int:pk>', views.blog_details, name='blog_details'),
]

contactapp/urls.py
from django.urls import path

from .import views

app_name='contactapp'

urlpatterns = [ 
    path('', views.contact, name='contactpage'),
    path('appoinment/', views.appoinment, name='appoinment_page'),
]
      

hms/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homeapp.urls')),
    path('profile/', include('profileapp.urls')),
    path('contact/', include('contactapp.urls')),
    path('blogs/', include('blogapp.urls')),

    path('summernote/', include('django_summernote.urls')),
]
if settings.DEBUG:
    #urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

homeapp/urls.py
from django.urls import path

from .import views

app_name='homeapp'

urlpatterns = [
    path('', views.home, name='homepage'),
    path('about/', views.about, name='aboutpage'),
    path('doctor/', views.doctor, name='doctorpage'),
    path('doctor/<int:pk>', views.doctor_details, name='doctor_details_page'),
    path('reviews/', views.review, name='reviewpage'),
    path('services/', views.services, name='services_page'),
    path('services_details/<int:pk>', views.services_details, name='services_details_page'),
    path('department/<int:pk>', views.department_details, name='departmentdetails'),
    path('test_price_list/', views.test_price_list, name='test_price_list'), 
    path('diagnostic/<int:pk>', views.diagnostic_details, name='diagnostic_details'),
    path('hospital/', views.hospital, name='hospital_page'),
    path('hospital/<int:pk>', views.hospital_details, name='hospital_details'),
] 

templates/global/footer.html
{% load static %}

{% block content %}

<section class="footer-call-to-action">
	<div class="container">
	   <div class="row">
		  <div class="col-md-9">
			 <h3>Book A Appointment With US</h3>
			 <p>There are many variations of passages of Lorem Ipsum available, but the majority have lorem</p>
		  </div>
		  <div class="col-md-3">
			 <a href="{% url 'contactapp:appoinment_page' %}" target="_blank" class="thm-btn inverse pull-right">Book Now</a> 
		  </div>
	   </div>
	</div>
 </section>

	<footer class="footer sec-pdd-90-85">
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-sm-6">
					<div class="footer-widget about-widget">
						<a href="#">
							<img src="img/resources/footer-logo.png" alt="Awesome Image"/>
						</a>
						<p>Lorem ipsum dolor sit amet, eu me evert laboramus, iudico </p>
						<ul class="contact">
							<li><i class="fa fa-map-marker"></i> <span>60 Grant Ave. Carteret NJ 0708</span></li>
							<li><i class="fa fa-phone"></i> <span>(880) 1723801729</span></li>
							<li><i class="fa fa-envelope-o"></i> <span>example@gmail.com</span></li>
						</ul>
						<ul class="social">
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							<li><a href="#"><i class="fa fa-pinterest"></i></a></li>
							<li><a href="#"><i class="fa fa-youtube"></i></a></li>
						</ul>
					</div>
				</div>
				<div class="col-md-4 col-sm-6">
					<div class="footer-widget quick-links">
						<h3 class="title">Depertments</h3>
						<ul>
						{% for depertment in depertments   %}
							<li><a href="{% url 'homeapp:departmentdetails' depertment.pk %}">{{depertment.name}}</a></li>
						{% endfor %}
						</ul>
					</div>
				</div>


				<div class="col-md-4 latest-post col-sm-6">
					<div class="footer-widget latest-post itm-mgn-top-50">
						<h3 class="title">Latest News</h3>
						<ul>
					
							{% for blog in blogs %}
							<li>
								<span class="border"></span>
								<div class="content">
									<a href="blog-details.html">{{blog.title|truncatechars_html:60}} </a>
									<span>{{blog.post_date}}</span>
								</div>
							</li>
							{% endfor %}
						
						</ul>
					</div>
				</div>
				{% comment %} <div class="col-md-4 col-sm-6">
					<div class="footer-widget contact-widget itm-mgn-top-50">
						<h3 class="title">Contact Form</h3>
						<form action="https://world5.commonsupport.com/jewel/Dentalclinic/inc/sendemail.php" class="contact-form" id="footer-cf">
							<input type="text" name="name"  placeholder="Full Name">
							<input type="text" name="email" placeholder="Email Address" >
							<textarea name="message" placeholder="Your Message"></textarea>
							<button type="submit">Send</button>
						</form>
					</div>
				</div> {% endcomment %}
			</div>
		</div>
	</footer>


	<section class="footer-bottom">
		<div class="container text-center">
			<p>Theme Created By <a href="#">Dhaka Solution</a> with love</p>
		</div>
	</section>

{% endblock %}

templates/global/navbar.html
{% load static %}

{% block content %}
	<section class="top-bar">
		<div class="container">

			<div class="left-text pull-left">
				<p><span>Opening Hours :</span> Monday to Saturday - 8am to 5pm</p>
			</div> <!-- /.left-text -->

			<div class="social-icons pull-right">
				<ul>
					<li><a href="#"><i class="fa fa-facebook"></i></a></li>
					<li><a href="#"><i class="fa fa-twitter"></i></a></li>
					<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
					<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
					<li><a href="#"><i class="fa fa-pinterest"></i></a></li>
				</ul>
			</div> <!-- /.social-icons -->
		</div>
	</section> <!-- /.top-bar -->

	<header class="header">
		<div class="container">
			<div class="logo pull-left">
				<a href="index.html">
					<img src="img/resources/logo.png" alt="Awesome Image"/>
				</a>
			</div>
			<div class="header-right-info pull-right clearfix">
				<div class="single-header-info">
					<div class="icon-box">
						<div class="inner-box">
							<i class="flaticon-symbol"></i>
						</div>
					</div>
					<div class="content">
						<h3>EMAIL</h3>
						<p>companyname@mail.com</p>
					</div>
				</div>
				<div class="single-header-info">
					<div class="icon-box">
						<div class="inner-box">
							<i class="flaticon-technology"></i>
						</div>
					</div>
					<div class="content">
						<h3>Call Now</h3>
						<p><b>(732) 803-010-03</b></p>
					</div>
				</div>
				<div class="single-header-info">
					<a href="{% url 'contactapp:appoinment_page' %}" class="thm-btn">Appointment</a>
				</div>
			</div>
		</div>
	</header> <!-- /.header -->


	<nav class="mainmenu-area stricky">
		<div class="container">
			<div class="navigation pull-left">
				<div class="nav-header"> 
					<ul>
				
						<li><a href="{% url 'homeapp:homepage' %}">Home</a></li>
						<li><a href="{% url 'homeapp:aboutpage' %}">About Us</a></li> 

						<li class="dropdown">
							<a href="#">Depertments</a>
							<ul class="submenu">
								{% for depertment in depertments   %}
								<li><a href="{% url 'homeapp:departmentdetails' depertment.pk %}">{{depertment.name}}</a></li>
								{% endfor %}
							</ul>
						</li> 

						<li class="dropdown">
							<a href="#">Diagnostic</a>
							<ul class="submenu">
								{% for diagnostic in diagnostics %}
								<li><a href="{% url 'homeapp:diagnostic_details' diagnostic.pk %}">{{diagnostic.name}}</a></li>
								{% endfor %}
							</ul>
						</li> 
				
						<li><a href="{% url 'homeapp:doctorpage' %}">Doctors</a></li> 
						<li><a href="{% url 'homeapp:hospital_page' %}">Hospital</a></li>   
						
						<li><a href="{% url 'homeapp:services_page' %}">Services</a></li>  
						<li><a href="{% url 'homeapp:test_price_list' %}">Price</a></li>
				
						<li><a href="{% url 'blogapp:blogs' %}">Blog</a></li>
						<li><a href="{% url 'contactapp:contactpage' %}">Contact Us</a></li>
					</ul>
				</div>
				<div class="nav-footer">
					<button><i class="fa fa-bars"></i></button>
				</div>
			</div>
			<div class="search-box pull-right navbar-box">
				<form action="#">
					<input type="text" placeholder="Search...">
					<button type="submit"><i class="fa fa-search"></i></button>
				</form>
			</div> 
	</nav> <!-- /.mainmenu-area -->

{% endblock %}

templates/global/thankyou.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>

/* thank you page */

.thanku {
  margin-top: 120px;
  margin-bottom: 120px;
}

.error-page {
  text-align: center;
  /* background: #fff; */
  border-top: 1px solid #eee;
}

.error-page .error-inner {
  display: inline-block;
}

.error-page .error-inner h1 {
  font-size: 140px;
  text-shadow: 3px 5px 2px #3333;
  color: #006DFE;
  font-weight: 700;
  line-height: 100px;
}

.error-page .error-inner h1 span {
  display: block;
  font-size: 25px;
  color: #333;
  font-weight: 600;
  text-shadow: none;
}

.text-content{
	display: block;
  font-size: 25px;
  color: #333;
  font-weight: 600;
  text-shadow: none;
	margin-top: 55px;
	margin-bottom: 55px;
}

.error-page .error-inner p {
  padding: 20px 15px;
}

.error-page .search-form {
  width: 100%;
  position: relative;
}

.error-page .search-form input {
  width: 400px;
  height: 50px;
  padding: 0px 78px 0 30px;
  border: none;
  background: #f6f6f6;
  border-radius: 5px;
  display: inline-block;
  margin-right: 10px;
  font-weight: 400;
  font-size: 14px;
}

.error-page .search-form input:hover {
  padding-left: 35px;
}

.error-page .search-form .btn {
  width: 80px;
  height: 50px;
  border-radius: 5px;
  cursor: pointer;
  background: #006DFE;
  display: inline-block;
  position: relative;
  top: -2px;
}

.error-page .search-form .btn i {
  font-size: 16px;
}

.error-page .search-form .btn:hover {
  background: #333;
}


</style>


<section class="error-page section">
  <div class="container">
	  <div class="row">
		  <div class="col-lg-12 offset-lg-12 col-12 thanku" >
			  <!-- Error Inner -->
			  <div class="error-inner">
				  <h1>Thank you!</h1>
				  <div class="text-content">
					<h4 >We will reach you soon.!</h4>
				  </div>
					  <button class="btn mt-3 mb-3" >
						<a href="{% url 'homeapp:homepage' %}">Back to homepage</a>
					</button>
			  </div>
			  <!--/ End Error Inner -->
		  </div>
	  </div>
  </div>
</section>


{% endblock %}